-- Migration 0008: Die gewählte Dokumentvorlage wird auch bei Angeboten
-- und Gutschriften dauerhaft am Beleg gespeichert.

PRAGMA foreign_keys = ON;

ALTER TABLE quote ADD COLUMN template_id TEXT REFERENCES document_template(id) ON DELETE SET NULL;
ALTER TABLE credit_note ADD COLUMN template_id TEXT REFERENCES document_template(id) ON DELETE SET NULL;

INSERT INTO app_migration (version, name, applied_at)
VALUES (8, '0008_belegvorlagen_und_din', datetime('now'));

-- Neue Installationen erhalten direkt auswählbare DIN-orientierte Vorlagen.
CREATE TEMP TABLE _seed_templates (enabled INTEGER NOT NULL);
INSERT INTO _seed_templates VALUES ((SELECT COUNT(*) = 0 FROM document_template));

INSERT INTO document_template (id,name,version,doc_types,is_default,layout_json,created_at,updated_at)
SELECT 'tpl-modern','Modern DIN',3,'invoice,quote,credit_note',1,'{"name":"Modern DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":9.5,"primaryColor":"#182230","secondaryColor":"#64748B","accentColor":"#4F46E5","variant":"modern","logoWidthMm":38,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now'),datetime('now')
FROM _seed_templates WHERE enabled=1;
INSERT INTO document_template_version (id,template_id,version,layout_json,created_at)
SELECT 'tpl-modern-v3','tpl-modern',3,'{"name":"Modern DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":9.5,"primaryColor":"#182230","secondaryColor":"#64748B","accentColor":"#4F46E5","variant":"modern","logoWidthMm":38,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now')
FROM _seed_templates WHERE enabled=1;

INSERT INTO document_template (id,name,version,doc_types,is_default,layout_json,created_at,updated_at)
SELECT 'tpl-classic','Klassisch DIN',3,'invoice,quote,credit_note',0,'{"name":"Klassisch DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Source Serif 4","baseFontSizePt":10,"primaryColor":"#1F2937","secondaryColor":"#6B7280","accentColor":"#1F2937","variant":"classic","logoWidthMm":34,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit_price","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now'),datetime('now')
FROM _seed_templates WHERE enabled=1;
INSERT INTO document_template_version (id,template_id,version,layout_json,created_at)
SELECT 'tpl-classic-v3','tpl-classic',3,'{"name":"Klassisch DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Source Serif 4","baseFontSizePt":10,"primaryColor":"#1F2937","secondaryColor":"#6B7280","accentColor":"#1F2937","variant":"classic","logoWidthMm":34,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit_price","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now')
FROM _seed_templates WHERE enabled=1;

INSERT INTO document_template (id,name,version,doc_types,is_default,layout_json,created_at,updated_at)
SELECT 'tpl-compact','Kompakt DIN',3,'invoice,quote,credit_note',0,'{"name":"Kompakt DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":8.5,"primaryColor":"#111827","secondaryColor":"#6B7280","accentColor":"#0F766E","variant":"compact","logoWidthMm":30,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now'),datetime('now')
FROM _seed_templates WHERE enabled=1;
INSERT INTO document_template_version (id,template_id,version,layout_json,created_at)
SELECT 'tpl-compact-v3','tpl-compact',3,'{"name":"Kompakt DIN","version":3,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":8.5,"primaryColor":"#111827","secondaryColor":"#6B7280","accentColor":"#0F766E","variant":"compact","logoWidthMm":30,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now')
FROM _seed_templates WHERE enabled=1;
DROP TABLE _seed_templates;
