-- Migration 0010: Zusaetzliche Vorlage "Modern Grün". Wird nicht als
-- Standard gesetzt (is_default=0), damit bestehende Belege unveraendert
-- bleiben - waehlbar ueber die Vorlagenverwaltung.

INSERT INTO app_migration (version, name, applied_at)
VALUES (10, '0010_moderne_gruene_vorlage', datetime('now'));

INSERT INTO document_template (id,name,version,doc_types,is_default,layout_json,created_at,updated_at)
SELECT 'tpl-green-modern','Modern Grün',1,'invoice,quote,credit_note',0,'{"name":"Modern Grün","version":1,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":9.5,"primaryColor":"#111827","secondaryColor":"#4B5563","accentColor":"#16A34A","variant":"modern","logoWidthMm":34,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now'),datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM document_template WHERE id='tpl-green-modern');

INSERT INTO document_template_version (id,template_id,version,layout_json,created_at)
SELECT 'tpl-green-modern-v1','tpl-green-modern',1,'{"name":"Modern Grün","version":1,"page":{"format":"A4","marginTopMm":16,"marginRightMm":20,"marginBottomMm":20,"marginLeftMm":25,"fontFamily":"Inter","baseFontSizePt":9.5,"primaryColor":"#111827","secondaryColor":"#4B5563","accentColor":"#16A34A","variant":"modern","logoWidthMm":34,"din5008":true},"header":[{"id":"logo","type":"logo","style":{"align":"right"}},{"id":"sender","type":"sender_line","content":"{{firma.name}} · {{firma.strasse}} · {{firma.plz}} {{firma.ort}}","style":{"fontSizePt":7}}],"body":[{"id":"address","type":"address"},{"id":"info","type":"document_info"},{"id":"intro","type":"text","content":"{{beleg.einleitung}}","style":{"marginTopMm":7,"marginBottomMm":6}},{"id":"items","type":"items_table","columns":["position","description","quantity","unit","unit_price","tax_rate","line_total"]},{"id":"totals","type":"totals","style":{"marginTopMm":7}},{"id":"tax","type":"tax_summary","style":{"marginTopMm":4}},{"id":"outro","type":"text","content":"{{beleg.schlusstext}}","style":{"marginTopMm":8}},{"id":"payment","type":"payment_info","content":"Zahlbar bis {{beleg.faelligAm}}. Bitte geben Sie {{beleg.nummer}} als Verwendungszweck an.","style":{"marginTopMm":5}}],"footer":[{"id":"divider","type":"divider"},{"id":"foot","type":"text","content":"{{firma.fusszeile}}","style":{"fontSizePt":7,"align":"center"}},{"id":"pages","type":"page_numbers","style":{"fontSizePt":7,"align":"center"}}],"watermark":"none"}',datetime('now')
WHERE NOT EXISTS (SELECT 1 FROM document_template_version WHERE id='tpl-green-modern-v1');
